language: php

php:
  - 5.5
  - hhvm

sudo: false

before_install:
  - composer self-update

install: 
  - travis_retry composer install --no-interaction --prefer-source

script: 
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)